# Build the main image.
FROM php:8.1.7-fpm-buster

ENV APP_PUBLIC_PATH=/var/www/mra/public
ENV COMPOSER_ALLOW_SUPERUSER=1
ENV APP_ID=mra-dev
ARG APP_VERSION
ENV APP_VERSION=$APP_VERSION

RUN apt update && apt install -y \
    curl \
    git \
    cron \
    # zip/unzip packages required for Composer in order to install packages.
    zlib1g-dev \
    libzip-dev \
    unzip \
    nginx \
    supervisor \
    # libicu-dev is a dependency required by the `intl` extension.
    libicu-dev \
    # ffmpeg is needed for combining Reddit video and audio asset files.
    ffmpeg

RUN docker-php-ext-install \
    pdo \
    intl \
    # sysvsem is required for the RateLimiter Semaphore store.
    sysvsem

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

RUN docker-php-ext-install zip

# Install Node.
# https://stackoverflow.com/a/77021599
# https://github.com/nodesource/distributions#installation-instructions
RUN set -uex; \
    apt-get install -y ca-certificates curl gnupg; \
    mkdir -p /etc/apt/keyrings; \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
     | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg; \
    NODE_MAJOR=20; \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" \
     > /etc/apt/sources.list.d/nodesource.list; \
    apt-get update; \
    apt-get install -y nodejs;

# Install Yarn.
RUN corepack enable \
    && corepack prepare yarn@stable --activate

# Clean up apt cache.
RUN rm -rf /var/lib/apt/lists/*

# Configure php.
COPY ./development/php.ini /usr/local/etc/php/php.ini

# Install Composer.
# https://stackoverflow.com/a/58694421
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
RUN echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $HOME/.profile

# Install Symfony installer.
RUN curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | bash && \
    apt install -y symfony-cli

# Cron setup.
ADD build/cron/crontab.txt /crontab.txt
RUN crontab /crontab.txt

# Configure Nginx.
COPY build/nginx-site.conf /etc/nginx/sites-enabled/default

# Configure Entrypoint.
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod u+x /entrypoint.sh

# Configure Supervisor.
RUN mkdir -p /var/log/supervisor
COPY ./build/supervisord.conf /etc/supervisor/supervisord.conf
COPY ./build/supervisord/cron.conf /etc/supervisor/conf.d/cron.conf

# Additional folder setup.
RUN mkdir /database
RUN mkdir /r-media

# Opinionated terminal styling choice.
RUN echo "export PS1='\[\e[36m\]\u:\W$ \[\e[0m\]'" >> $HOME/.profile

ENTRYPOINT ["/entrypoint.sh"]