openapi: 3.0.0
info:
  title: My Reddit Archive API
  description: My local API for accessing my Reddit Profile `Saved` contents.
  version: "0.1"
servers:
  - url: /api
    description: Main API endpoint base.
paths:
  /contents:
    get:
      summary: Returns a list of `Saved` contents.
      description: Retrieve a listing of `Saved` contents as filtered and sorted by optional parameters.
      responses:
        '200':    # status code
          description: A JSON array of `Saved` contents.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Content'

components:
  schemas:
    Content:
      type: object
      properties:
        id:
          type: integer
        kind:
          $ref: '#/components/schemas/Kind'
    Kind:
      type: object
      properties:
        redditId:
          type: string
          enum: ["t1", "t3"]
        name:
          type: string
          enum: ["Comment", "Link"]