version: '3.9'

services:
  mra-api:
    container_name: mra-api
    image: mra:local
    volumes:
      - ./api/app:/var/www/mra-api
      - /var/www/mra-api/node_modules/
      - /var/www/mra-api/vendor/
      - /var/www/mra-api/var/
    environment:
      REDDIT_USERNAME: "${REDDIT_USERNAME}"
      REDDIT_PASSWORD: "${REDDIT_PASSWORD}"
      REDDIT_CLIENT_ID: "${REDDIT_CLIENT_ID}"
      REDDIT_CLIENT_SECRET: "${REDDIT_CLIENT_SECRET}"
      DATABASE_URL: "${DATABASE_URL}"
      PHP_IDE_CONFIG: "${PHP_IDE_CONFIG}"
    working_dir: /var/www/mra-api
  mra-api-web: 
    container_name: mra-api-web
    image: nginx:alpine
    volumes:
      - ./api/app:/var/www/mra-api
      - ./api/main.conf:/etc/nginx/conf.d/default.conf
      # - ./web/certs/local.crt:/etc/ssl/certs/local.crt
      # - ./web/certs/local.key:/etc/ssl/private/local.key
    ports:
      - "2080:80"
      # - "1002:443"
  mra-database:
    container_name: mra-database
    image: mariadb:10.8
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
    ports:
      - "3116:3306"
    volumes:
      - ./database-data:/var/lib/mysql
    working_dir: /var/lib/mysql