version: '3.9'

services:
  mra:
    container_name: mra
    image: javenlalla/mra
    volumes:
      - </path/to/media>:/var/www/mra/public/r-media
    env_file: .env
    ports:
      - "3580:80" # Adjust port as needed.