version: '3.9'

services:
  mra-api:
    container_name: mra-api
    build:
      context: ./build
      dockerfile: Dockerfile
      tags:
        - "mra-api:main"
    volumes:
      - ./api/app:/var/www/mra-api
      - /var/www/mra-api/node_modules/
      - /var/www/mra-api/var/
    working_dir: /var/www/mra-api
    environment:
      REDDIT_USERNAME: "REPLACE_REDDIT_USERNAME"
      REDDIT_PASSWORD: "REPLACE_REDDIT_PASSWORD"
      REDDIT_CLIENT_ID: "REPLACE_REDDIT_CLIENT_ID"
      REDDIT_CLIENT_SECRET: "REPLACE_REDDIT_CLIENT_SECRET"
      DATABASE_URL: "mysql://REPLACE_MARIADB_USER:REPLACE_MARIADB_PASSWORD@mra-database:3306/REPLACE_MARIADB_DATABASE?serverVersion=mariadb-10.8.3&charset=utf8mb4"
      # Development Only
      # PHP_IDE_CONFIG: "serverName=my-development-domain.com"
  mra-api-web: 
    container_name: mra-api-web
    image: nginx:alpine
    volumes:
      - ./api/app:/var/www/mra-api
      - ./api/main.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "2080:80"
  mra-database:
    container_name: mra-database
    image: mariadb:10.8
    working_dir: /var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "REPLACE_MARIADB_ROOT_PASSWORD"
      MARIADB_USER: "REPLACE_MARIADB_USER"
      MARIADB_PASSWORD: "REPLACE_MARIADB_PASSWORD"
      MARIADB_DATABASE: "REPLACE_MARIADB_DATABASE"
    volumes:
      - ./database-data:/var/lib/mysql
  mra-cache:
    container_name: mra-cache
    image: redis:7-alpine