version: '3.9'

services:
  mra-api: #Update Service Name
    container_name: mra-api #Update Container Name
    image: mra:local
    volumes:
      - ./api/app:/var/www/mra-api
      - /var/www/mra-api/node_modules/
      - /var/www/mra-api/vendor/
      - /var/www/mra-api/var/
    environment:
      PHP_IDE_CONFIG: "${PHP_IDE_CONFIG}" #Update Host Name
    working_dir: /var/www/mra-api
  mra-api-web:  #Update Service Name
    container_name: mra-api-web #Update Container Name
    image: nginx:alpine
    volumes:
      - ./api/app:/var/www/mra-api
      - ./api/main.conf:/etc/nginx/conf.d/default.conf
      # - ./web/certs/local.crt:/etc/ssl/certs/local.crt
      # - ./web/certs/local.key:/etc/ssl/private/local.key
    ports:
      - "2080:80"
      # - "1002:443"
  mra-database: #Update Service Name
    container_name: mra-database #Update Container Name
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - "3116:3306" #Update Port
    volumes:
      - ./database-data:/var/lib/mysql
    working_dir: /var/lib/mysql
  # smsweets-react: #Update Service Name
  #   container_name: smsweets-react #Update Container Name
  #   image: node:16-alpine3.12
  #   volumes:
  #     - ./smsweets:/var/www/smsweets
  #   working_dir: /var/www/smsweets
  #   ports:
  #     - "8080:8080"