# Build the main image.
FROM php:8.3.6-fpm-bookworm

ENV APP_ENV=test
ENV APP_PUBLIC_PATH=/var/www/mra/public
ENV COMPOSER_ALLOW_SUPERUSER=1
ENV APP_ID=mra
ARG APP_VERSION
ENV APP_VERSION=$APP_VERSION
# Disable deprecation notices for automated testing/CI flows.
ENV SYMFONY_DEPRECATIONS_HELPER=disabled=1

RUN apt update && apt install -y \
    curl \
    git \
    cron \
    # zip/unzip packages required for Composer in order to install packages.
    zlib1g-dev \
    libzip-dev \
    unzip \
    nginx \
    supervisor \
    # libsqlite3-dev is required by the `pdo_sqlite` extension.
    libsqlite3-dev \
    # libicu-dev is a dependency required by the `intl` extension.
    libicu-dev \
    # ffmpeg is needed for combining Reddit video and audio asset files.
    ffmpeg

RUN docker-php-ext-install \
    pdo \
    pdo_sqlite \
    pdo_mysql \
    intl \
    # sysvsem is required for the RateLimiter Semaphore store.
    sysvsem

RUN docker-php-ext-install zip

# Clean up apt cache.
RUN rm -rf /var/lib/apt/lists/*

# Configure php.
COPY ./development/php.test.ini /usr/local/etc/php/php.ini

# Install Composer.
# https://stackoverflow.com/a/58694421
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
RUN echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $HOME/.profile

# Copy application to image.
RUN mkdir /var/www/mra/
COPY src /var/www/mra
WORKDIR /var/www/mra
RUN rm -rf var

RUN cp .env.sample .env
RUN composer install

# Fix folder permissions.
RUN chown -R www-data:www-data /var/www/mra

# Configure Entrypoint.
COPY entrypoint.sh /entrypoint.sh
RUN chmod u+x /entrypoint.sh

# Configure Supervisor.
RUN mkdir -p /var/log/supervisor
COPY ./development/supervisord.test.conf /etc/supervisor/supervisord.conf

# Additional folder setup.
RUN mkdir /database

ENTRYPOINT ["/entrypoint.sh"]