version: '3.9'

services:
  mra:
    container_name: mra
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/r-media:/var/www/mra/public/r-media
    env_file: .env
    ports:
      - "2080:80" # Adjust port as needed.

  # If desired to use this database, uncomment and provide a secure
  # password for the `MARIADB_ROOT_PASSWORD` Environment variable.
  # mra-db:
  #   container_name: mra-db
  #   image: mariadb:10.8.6
  #   env_file: .env
  #   environment:
  #     MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #     MARIADB_USER: ${DB_USERNAME}
  #     MARIADB_PASSWORD: ${DB_PASSWORD}
  #     MARIADB_DATABASE: ${DB_DATABASE}
  #   volumes:
  #     - ./data/db:/var/lib/mysql