framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: app/mra

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        app: cache.adapter.doctrine_dbal
        default_pdo_provider: 'doctrine.dbal.default_connection'

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        pools:
            app.cache.pool:
                adapter: cache.app
                default_lifetime: 600

            reddit_api_rate_limiter.cache:
                adapter: cache.app

when@test:
    framework:
        cache:
            pools:
                app.cache.pool:
                    adapter: cache.adapter.array