services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true

    App\Service\Typesense\Search:
        public: true

    App\Service\Reddit\Manager\BatchSync:
        public: true

    App\Service\Reddit\Items:
        public: true